name: go_build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Go-build on  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest,ubuntu-latest,macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go-build
      run: go build
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: ebiten-cli-${{ matrix.os }}-go1.17
        path: |
          ebiten-cli
          ebiten-cli.exe
